config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/about", to: "pages#about"
  get "/contacts", to: "pages#contacts"
  get "/productos", to: "pages#productos"
  get "/services", to: "pages#services"
  get "/catalogos", to: "pages#catalogos"
  get "/products", to: "pages#products"
  get "/repuestos", to: "pages#repuestos"
  get 'download_pdf', to: "pages#download_pdf"
  get 'send_email', to: "pages#send_email"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about, :contacts, :catalogos, :services, :products, :productos, :repuestos, :send_email, :download_pdf]

  def home
  end

  def about
  end

  def contacts
  end

  def services
  end

  def products
  end

  def repuestos
  end

  def send_email
    contacts = params["contacts"]
    UserMailer.send_email_to_contact(contacts).deliver_now
    redirect_to root_path
  end

  def download_pdf
    send_file "#{Rails.root}/app/assets/images/#{params[:name]}.pdf", type: "application/pdf", x_sendfile: true
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>COLCRANES</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.0/css/swiper.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.0/css/swiper.min.css">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.0/js/swiper.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.0/js/swiper.min.js"></script>

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= favicon_link_tag asset_path 'favicon.png' %>
    <% if current_page?(controller: 'pages', action: 'contacts') %>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <% end %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/catalogos.html.erb
<div class="catalogos">
  <div class="catalogos-banner">
    <h3>Descarga Nuestros Catalogos</h3>
  </div>
  <div class="catalogos-content">
    <%= image_tag 'colcranes-new.png' %>
    <div class="catalogos-botones">
      <%= link_to download_pdf_path + "?name=presentacion_corporativa", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Presentacion Corporativa</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
      <%= link_to download_pdf_path + "?name=catalogo_de_productos", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Catalogo De Productos</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
    </div>
  </div>
  <div class="catalogos-content">
    <%= image_tag 'rmlogo.png' %>
    <div class="catalogos-botones">
      <%= link_to download_pdf_path + "?name=brochure_randm", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Brochure-R&M</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
      <%= link_to download_pdf_path + "?name=linea_de producto", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Linea de Productos</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
      <%= link_to download_pdf_path + "?name=spacemaster_sx", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Spacemaster SX</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
      <%= link_to download_pdf_path + "?name=spacemaster_sxl", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Spacemaster SXL</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
    </div>
  </div>
  <div class="catalogos-content">
    <%= image_tag 'black-bear.png' %>
    <div class="catalogos-botones">
      <%= link_to download_pdf_path + "?name=air_chain_hoist", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Air Chain Host</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
      <%= link_to download_pdf_path + "?name=hand_chain_lever_hoist", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Hand Chain & Lever Hoist</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
      <%= link_to download_pdf_path + "?name=eletric_chain_hoist", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Electric Chain Hoist</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
      <%= link_to download_pdf_path + "?name=electric_chain_hoist_hnd", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Electric Chain Hoist NHD</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
    </div>
  </div>
  <div class="catalogos-content">
    <%= image_tag 'conductix.png' %>
    <div class="catalogos-botones">
      <%= link_to download_pdf_path + "?name=energy_data_transmission_systems", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Energy & Data Transmission Systems</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
      <%= link_to download_pdf_path + "?name=spring_driven_cable_reels", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Spring Driven Cable Reels</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
      <%= link_to download_pdf_path + "?name=conductor_bar", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Conductor Bar</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
      <%= link_to download_pdf_path + "?name=cable_festoon_systems", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Cable Festoon Systems</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
      <%= link_to download_pdf_path + "?name=push_button_pendants", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Push Button Pendants</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
      <%= link_to download_pdf_path + "?name=saga_radio_remote_controls", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Saga Radio Remote Controls</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
      <%= link_to download_pdf_path + "?name=spring_balancers", class: "catalogos-link" do %>
        <button class="catalogo"><span style="flex: 1;">Spring Balancers</span><i class="fas fa-arrow-alt-circle-down"></i></button>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="contact-us-banner">
  <div class="contact-us-container">
    <div class="contact-contactanos">
      <h1>Contactanos</h1>
      <p>5 anños de experiencia en adminsitracion de bienes industriales</p>
    </div>
    <div class="contact-us-form-wrapper">
      <div class="contact-us-form">
        <div class="contact-form-left">
          <%= simple_form_for '/contact', url: contact_path do |f| %>
            <%= f.input :name, label: false, placeholder:'Primer Nombre y Apellido', input_html: { class: "contact-form-name contact-form-input" } %>
            <%= f.input :email, label: false, placeholder:'Direccion de Correo', input_html: { class: "contact-form-name contact-form-input" } %>
            <%= f.input :message, as: :text, label: false, placeholder:'Mensaje', input_html: { class: "contact-form-message contact-form-input" } %>
            <%= f.button :button, type: :submit,  class: "contact-form-button" do %>
              <p>Enviar</p>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="contact-us-form-info">
        <h1>Informacion</h1>
        <div class="form-info-container">
        <div class="form-info-content" style="align-items: center;">
          <i  style="height: 33%;" class="fas fa-map-pin form-info-icon"></i>
          <i  style="height: 33%; display: flex; align-items: center;" class="fas fa-phone form-info-icon"></i>
          <i  style="height: 33%; display: flex; align-items: flex-end;" class="fas fa-envelope form-info-icon"></i>
        </div>
        <div class="form-info-content" style="margin-left: 5px;">
          <p style="height: 33%;" >Calle 45 no 28-23 Barranquilla, Colombia 25213</p>
          <p style="height: 33%; display: flex; align-items: center;" >055-233-5544</p>
          <p style="height: 33%; display: flex; align-items: flex-end;" >Contactz@colcranes.com</p>
        </div>
        </div>
        <div class="contact-form-social-links">
          <i class="fab fa-facebook"></i>
          <i class="fab fa-instagram"></i>
          <i class="fab fa-linkedin"></i>
        </div>
      </div>
    </div>
    <div class="contact-info">
      <div>
        <p><span><i class="fas fa-phone form-info-icon"></i></span>Mantenimiento: 555-333-1212</p>
      </div>
      <div>
        <p><span><i class="fas fa-phone form-info-icon"></i></span>Vespas: 555-333-1212</p>
      </div>
      <div>
        <p><span><i class="fas fa-phone form-info-icon"></i></span>Repuestos: 555-333-1212</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/contacts.html.erb
<div class="contact-us-banner">
  <div class="contact-us-container">
    <div class="contact-contactanos">
      <h1 class="no-margin">Contactanos</h1>
      <p>Para informarcion general escribanos a info@colcranes.com </p>
    </div>
    <div class="contact-us-form-wrapper">
      <div class="contact-us-form">
        <div class="contact-form-left">
          <%= simple_form_for :send_email, url: send_email_path, method: :get do |f| %>
            <h2>Envianos un Mensaje</h2>
            <div class="contact-form-middle">
              <div class="input-field contacts_name">
                <input class="form-control string required contact-form-name contact-form-input" type="text" name="contacts[name]" id="contacts_name">
                <label id="contacts_name" class="label-contact-name" for="contacts_name">Primer Nombre y Apellido</label>
              </div>
              <div class="input-field contacts_email">
                <input class="form-control string email required contact-form-email contact-form-input" type="email" name="contacts[email]" id="contacts_email">
                <label id="contacts_email" class="label-contact-email" for="contacts_email">Direccion de Correo</label>
              </div>
              <div class="input-field contacts_message">
                <textarea class="form-control text required contact-form-message contact-form-input materialize-textarea" name="contacts[message]" id="contacts_message"></textarea>
                <label id="contacts_message" class="label-contact-message" for="contacts_message">Mensaje</label>
              </div>
            </div>
            <%= f.button :button, type: :submit,  class: "contact-form-button" do %>
              <%= image_tag "send.png", class: "contact-form-button-image" %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="contact-us-form-info">
        <h1 class="no-margin">Informacion</h1>
        <div class="form-info-container">
          <div class="form-info-content" style="align-items: center;">
            <i  style="height: 33%;" class="fas fa-map-pin form-info-icon"></i>
            <i  style="height: 33%; display: flex; align-items: center;" class="fas fa-phone form-info-icon"></i>
            <i  style="height: 33%; display: flex; align-items: flex-end;" class="fas fa-envelope form-info-icon"></i>
          </div>
          <div class="form-info-content" style="margin-left: 5px;">
            <p style="height: 33%;" >Carrera 67 # 40 -62 piso 3 Barranquilla - Colombia</p>
            <p style="height: 33%; display: flex; align-items: center;" >+57 310 704 3333</p>
            <p style="height: 33%; display: flex; align-items: flex-end;" >ventas@colcranes.com</p>
          </div>
        </div>
        <div class="contact-form-social-links">
          <i class="fab fa-facebook"></i>
          <i class="fab fa-instagram"></i>
          <i class="fab fa-linkedin"></i>
        </div>
      </div>
    </div>
    <div class="contact-info">
      <div>
        <p><span><i class="fas fa-phone form-info-icon form-phone-icon"></i> </span>Contabilidad: +57 321 815 0272</p>
      </div>
      <div>
        <p><span><i class="fas fa-phone form-info-icon form-phone-icon"></i> </span>Ventas: +57 310 704 3333</p>
      </div>
      <div>
        <p><span><i class="fas fa-phone form-info-icon form-phone-icon"></i> </span>Soporte: +57 314 507 3092</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="home-banner-container">
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel" data-pause="false">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="home-banner home-banner-one"></div>
      </div>
      <div class="carousel-item">
        <div class="home-banner home-banner-two"></div>
      </div>
      <div class="carousel-item">
        <div class="home-banner home-banner-three"></div>
      </div>
    </div>
  </div>
  <div class="banner-gradient"></div>
  <div class="home-banner-content">
    <div style="width: 100%;">
      <h1>SIRVIENDO A</h1>
      <h1>COLOMBIA Y AL MUNDO</h1>
      <hr>
    </div>
    <p>
      Contamos con un equipo de trabajo con más de 35 años de experiencia en el mercado de los puentes grúa y polipastos, que se convierte en nuestra mejor carta de presentación.
    </p>
    <%= link_to 'CONTACTAR', contacts_path, class: "home-banner-button" %>
  </div>
</div>
<div class="container">
  <div class="text-section">
    <div class="text-section-text">
      <p>
        Somos una fabrica de soluciones en la linea de Puentes Grua. COLCRANES SAS brindar soluciones a la medida de nuestros clientes. Desde el cálculo estructural, fabricación y montaje de columnas, bodegas completas, fabricación y montaje de vigas carrileras, riel de rodadura, vigas puente y puesta en marcha de las grúas.
        <br><br>
        </p>
    </div>
  </div>
  <div class="credentials-section">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-lg-3">
        <div class="each-credential">
          <div class="yellow-circle">
            <%= image_tag 'certifiacon.png', class: "yellow-circle-icon" %>
          </div>
          <div class="credential-title">
            <h6>PERSONAL CERTIFICADO</h6>
          </div>
          <div class="credential-text">
            <p>Contamos con personal capacitado y entrenado constantemente en materia tecnomecanica. El equpo COLCRANES cuenta con Ingenieros Industriales, Mecanicos y Electricos preparados para proveer el mejor servicio.</p>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-lg-3">
        <div class="each-credential">
          <div class="yellow-circle">
            <%= image_tag 'cubrimiento-nacional.png', class: "yellow-circle-icon" %>
          </div>
          <div class="credential-title">
            <h6>CUBRIMIENTO NACIONAL</h6>
          </div>
          <div class="credential-text">
            <p>Gracias a nuestro equipo de logistica y transporte podemos alcanzar todos los rincones del pais. Nuestros operadores logisticos permiten que todos los productos sean enviados eficiente y eficazmente.</p>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-lg-3">
        <div class="each-credential">
          <div class="yellow-circle">
            <%= image_tag 'garantia-americana.png', class: "yellow-circle-icon" %>
          </div>
          <div class="credential-title">
            <h6>GARANTIA INTERNACIONAL</h6>
          </div>
          <div class="credential-text">
            <p>Cada uno de nuestros proveedores certifica y garantiza la calidad de sus productso es por eso que tramitamos garantias internacionales homologadas en el mercado Colombiano.</p>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-lg-3">
        <div class="each-credential">
          <div class="yellow-circle">
            <%= image_tag 'mantenimiento-anual.png', class: "yellow-circle-icon" %>
          </div>
          <div class="credential-title">
            <h6>MANTENIMIENTO ANUAL</h6>
          </div>
          <div class="credential-text">
            <p>
              Nuestro productos cuentan con garantias que proveen mantenimiento anual en sus equipos. El equpo tecnico de COLCRANES esta entrenado en areas electricas y mecanicas que garantizan la operacion de sus equipos.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= image_tag 'colcranes-line-break.png', class: "colcranes-line-break" %>
  <div class="recent-works-container">
    <h5 class="home-title">NUESTRAS INSTALACIONES</h5>
    <div class="row">
      <div class="hidden-xs hidden-sm col-xs-12 col-sm-6 col-lg-4 recent-works-image">
        <%= image_tag 'trabojos-1.jpg' %>
      </div>
      <div class="col-xs-12 col-sm-6 col-lg-4 recent-works-image">
        <%= image_tag 'trabojos-2.jpg' %>
      </div>
      <div class="col-xs-12 col-sm-6 col-lg-4 recent-works-image">
        <%= image_tag 'trabojos-3.jpg' %>
      </div>
    </div>
  </div>
  <hr class="colcranes-line-break">
  <div class="home-products-container">
    <div class="home-products-content">
      <h5 class="home-title">PRODUCTOS</h5>
      <p class="home-products-text">COLCRANES SAS en la línea de puentes grúa ofrece: puente grúas monorriel y/o birriel, grúas pórtico, gruas semi pórtico, grúas bandera ( Jib Cranes ) y estaciones de trabajo entre otrosa</p>
      <%= link_to 'Todos los Productos', products_path, class: "home-products-link" %>
    </div>
    <%= image_tag 'home-products-crane.png' %>
  </div>
  <%= image_tag 'colcranes-line-break.png', class: "colcranes-line-break" %>
  <div class="home-services-container">
    <%= image_tag 'home-services-man.png' %>
    <div class="home-services-content">
      <h5 class="home-title">SERVICIOS</h5>
      <p class="home-services-text"> COLCRANES SAS cuenta con una selección estratégica de proveedores aliados, que nos permite brindar soluciones a la medida de nuestros clientes. Desde el cálculo estructural, fabricación y montaje de columnas, bodegas completas, fabricación y montaje de vigas carrileras, riel de rodadura, vigas puente y puesta en marcha de las grúas.</p>
      <%= link_to 'Todos los Servicios', services_path, class: "home-services-link" %>
    </div>
  </div>
  <hr class="colcranes-line-break">
  <div class="home-facts-main-container">
    <div class="row">
      <div class="col-xs-12 col-lg-4">
        <div class="home-facts-container">
          <div class="home-facts-content">
            <p style="color: #454647; margin: 0;">Agosto</p>
            <h6 style="color: #454647;">26</h6>
            <p style="text-align: justify;">Nos preparamos para el lanzamiento de nuestro nuevo portal virtual que le permitara realizar ventas virtuales.</p>
            <hr class="home-facts-line-break">
            <p style="color: #454647;">contactanos</p>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-lg-4">
        <div class="home-facts-container">
          <div class="home-facts-content">
            <p style="color: #454647; margin: 0;">Noviembre</p>
            <h6 style="color: #454647;">11</h6>
            <p style="text-align: justify;">COLCRANES esta orgulloso de presentar su nueva linea de controles con bateria de litio para el ahorro de energia y mejora en tiempos de operacion.</p>
            <hr class="home-facts-line-break">
            <p style="color: #454647;">contactanos</p>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-lg-4">
        <div class="home-facts-container">
          <div class="home-facts-content">
            <p style="color: #454647; margin: 0;">Diciembre</p>
            <h6 style="color: #454647;">05</h6>
            <p style="text-align: justify;">Nos preparamos para entrenamiento tecnico. Estamos a la vanguardia de las practicas mas actualizadas en movimiento y carga de materiales pesados.</p>
            <hr class="home-facts-line-break">
            <p style="color: #454647;">contactanos</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-info-container">
    <div class="footer-logo">
      <%= image_tag 'colcranes-footer-new.png' %>
    </div>
    <div class="footer-info">
      <div class="paginas">
        <p class="footer-info-header">PAGINAS</p>
        <%= link_to about_path do %>
          <p style="font-size: 12px;">Acerca</p>
        <% end %>
        <%= link_to contacts_path do %>
          <p style="font-size: 12px;">Contacto</p>
        <% end %>
        <%= link_to services_path do %>
          <p style="font-size: 12px;">Servicios</p>
        <% end %>
        <%= link_to download_pdf_path + "?name=politica_anticorrupcion_antisoborno" do %>
          <p style="font-size: 12px;">Politica Anticorrupcion Antisoborno</p>
        <% end %>
      </div>
      <div class="contacto">
        <p class="footer-info-header">CONTACTO</p>
        <p style="font-size: 12px;">ventas@colcranes.com</p>
        <p style="font-size: 12px;">Carrera 67 # 40 -62 piso 3</p>
        <p style="font-size: 12px;">Barranquilla, Colombia</p>
      </div>
      <div class="contacto">
        <p class="footer-info-header">INFORMACIÓN</p>
        <p style="font-size: 12px; color: white;">+57 310 704 33 33</p>
        <p style="font-size: 12px; color: white;">+57 314 507 3092</p>
        <p style="font-size: 12px; color: white;">+57 5 318 56 58 ext 303</p>
      </div>
    </div>
  </div>
  <div class="foter-info-container-mobile">
    <%= image_tag 'colcranes-footer-mobile-new.png', height: 100; %>
    <p style="font-size: 12px; color: white;">Ventas: +57 310 704 3333</p>
    <p style="font-size: 12px; color: white;">Contabilidad: +57 321 815 0272</p>
    <p style="font-size: 12px; color: white;">ventas@colcranes.com</p>
  </div>
</div>
<div class="seo">
  <p>Desarrollado por: <%= link_to 'Hoxton Digital', 'https://www.hoxton-digital.com', target: "_blank" %></p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "colcranes-new.png" %>
    <% end %>
    <div class="colcranes-navbar-links-container">
      <%= link_to "NOSOTROS", about_path, class: "colcranes-navbar-link" %>
      <%= link_to "PRODUCTOS", productos_path, class: "colcranes-navbar-link" %>
      <%= link_to "SERVICIOS", services_path, class: "colcranes-navbar-link" %>
      <%= link_to "CATÁLOGOS", catalogos_path, class: "colcranes-navbar-link" %>
      <%= link_to "CONTÁCTENOS", contacts_path, class: "colcranes-navbar-link" %>
    </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    MENU
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="colcranes-navbar-links-container-dropdown">
          <%= link_to "ACERCA DE", about_path, class: "colcranes-navbar-link" %>
          <%= link_to "PRODUCTOS", productos_path, class: "colcranes-navbar-link" %>
          <%= link_to "SERVICIOS", services_path, class: "colcranes-navbar-link" %>
          <%= link_to "CATALOGOS", catalogos_path, class: "colcranes-navbar-link" %>
          <%= link_to "CONTACTO", contacts_path, class: "colcranes-navbar-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>